### ISSUE TITLE
Causes list-collapse-indicator exception

### ISSUE THREAD

**Issue by michaellw** [christianwannerstedt/obsidian-tags-overview#2] opened 2023-10-08 01:34 UTC
Thank you developer, it's really great plugin, but I'm having a problem with it, when I enable the plugin it causes an exception with list-collapse-indicator, I don't know what the problem is!
Please refer to the following video

https://github.com/christianwannerstedt/obsidian-tags-overview/assets/276357/89dc6077-e744-48df-a3fe-ddd51984a11d

**Comment by christianwannerstedt** [comment] 2023-10-09 21:01
Thanks for bringing this to my attention. It turned out to be due to an issue where the styling in this plugin was not properly wrapped in a namespace and therefore affected styling outside of it, in this case the collapse icon.

The issue is now fixed in version [0.1.3](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.3), so it should work fine if you just update the plugin.

**Closed** 2023-10-10 01:40 UTC
